spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  session:
    store-type: none

security:
  basic:
    enabled: false

server:
  port: 80
hommin:
  security:
    browser:
      loginType: JSON
    code:
      image:
        length: 6
        witeh: 100
        url: /user/*
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        filter-processes-url: /qqLogin
        provider-id: callback.do
        sign-up-url: /demo-sign-up.html
