spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  session:
    store-type: REDIS
  redis:
    host: 10.64.4.9
    password: rediszaq1

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: home
      client-secret: hehe

server:
  port: 80
hommin:
  security:
    browser:
      login-type: REDIRECT
      logout-success-url: /demo-logout.html
      delete-cookie: JSESSIONID,_gid
      login-page: /demo-sign-in.html
    code:
      image:
        length: 4
        witeh: 100
        url: /user/*
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        filter-processes-url: /qqLogin
        provider-id: callback.do
        sign-up-url: /demo-sign-up.html
